company.web/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Company.Data.Entities;
using Company.Services.Interfaces;
using Company.Services.Dto;

namespace company.web.Controllers
{
    public class DepartmentController : Controller
    {
        public readonly IDepartmentService _departmentService;
        public DepartmentController(IDepartmentService depService)
        {
            _departmentService = depService;
        }
        public IActionResult Index()
        {
            var dep = _departmentService.GetAll();
            return View(dep);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(DepartmentDto dep)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _departmentService.Add(dep);
                    return RedirectToAction(nameof(Index));
                }
                return View(dep);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("DepError", ex.Message);
                return View(dep);

            }

        }

        public IActionResult Details(int id)
        {
            // Fetch the department with the given ID
            var department = _departmentService.GetById(id);
            // Check if the department exists
            if (department is null)
            {
                return NotFound(); // Return a 404 if no department is found
            }
            // Pass the department data to the view
            return View(department);
        }
        public IActionResult GetDepartment()
        {
            var department = _departmentService.GetAll();
            return Json(department);  // Returns JSON data
        }

        public IActionResult Update(int id)
        {
            var department = _departmentService.GetById(id);
            return View(department);
        }

        [HttpPost]
        public IActionResult Update(DepartmentDto dep)
        {
            try
            {
                //var department = _departmentService.GetById(id);
                _departmentService.Update(dep);
                return View("Index", _departmentService.GetAll());
            }
            catch (ArgumentException ex)
            {
                TempData["Error"] = ex.Message;
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An unexpected error occurred: " + ex.Message;
            }
            return View("Edit", dep);




        }

        public IActionResult Delete(DepartmentDto dep)
        {
            var department = _departmentService.GetById(dep.Id);
            if (department is null)
            {
                return NotFound();
            }
            else
            {
                _departmentService.Delete(dep);

                return RedirectToAction(nameof(Index));
            }
        }
    }
}

company.web/Controllers/EmployeeController.cs
using AutoMapper;
using Company.Data.Entities;
using Company.Services.Dto;
using Company.Services.Interfaces;
using Company.Services.Services;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace company.web.Controllers
{
    public class EmployeeController : Controller
    {
        public readonly IEmployeeService _EmpService;
        public readonly IDepartmentService _depService;
        public readonly IMapper _mapper;
        public EmployeeController(IEmployeeService empService, IDepartmentService depService,IMapper mapper)
        {
            _EmpService = empService;
            _depService = depService;
            _mapper = mapper;
        }
        public IActionResult Index(string searchInp)
        {
            Console.WriteLine("employee index");
            if (searchInp == null)
            {
                var emp = _EmpService.GetAll();

                return View(emp);
            }
            else
            {
                var emp = _EmpService.GetEmployeeByName(searchInp);

                return View(emp);
            }
        }


        public IActionResult Create()
        {
            ViewBag.Departments = _depService.GetAll();

            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeDto emp)
        {

            try
            {
                emp.Department = _depService.GetById(emp.DepartmentId);
                if (ModelState.IsValid)
                {

                    _EmpService.Add(emp);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }

                }
                return View(emp);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("DepError", ex.Message);

                return View(emp);

            }

        }
    }
}

company.web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using company.web.Models; // If you have a folder where models are stored
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace company.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        // GET: Role
        public async Task<IActionResult> Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        // GET: Role/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Role/Create
        [HttpPost]
        public async Task<IActionResult> Create(string roleName)
        {
            if (!string.IsNullOrWhiteSpace(roleName))
            {
                var roleExists = await _roleManager.RoleExistsAsync(roleName);
                if (!roleExists)
                {
                    var result = await _roleManager.CreateAsync(new IdentityRole(roleName));
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Error creating role.");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Role already exists.");
                }
            }
            else
            {
                ModelState.AddModelError("", "Role name cannot be empty.");
            }
            return View();
        }

        // GET: Role/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var role = await _roleManager.FindByIdAsync(id);
                if (role != null)
                {
                    return View(role);
                }
            }
            return RedirectToAction("Index");
        }

        // POST: Role/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Error deleting role.");
                }
            }
            return View();
        }
    }
}

company.web/Controllers/UserController.cs
using Company.Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace company.web.Controllers
{
    //[Authorize(Roles="Admin")]
    public class UserController : Controller
    {

        public UserController(UserManager<ApplicationUser> userManger)
        {
            _UserManger = userManger;
        }

        public UserManager<ApplicationUser> _UserManger { get; }

        public async Task<IActionResult> Index(string searchInput)
        {
            List<ApplicationUser> users;
            if (string.IsNullOrEmpty(searchInput))
            {
                users = await _UserManger.Users.ToListAsync();
            }
            else
            {
                users =await _UserManger.Users.Where(user=>  user.NormalizedEmail.Trim().ToUpper() == searchInput.Trim().ToUpper()).ToListAsync();
            }
            return View(users);
        }
    }
}

company.web/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V3</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/png" href="~images/icons/favicon.ico" />

    <link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="~/fonts/iconic/css/material-design-iconic-font.min.css">

    <link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">

    <link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">

    <link rel="stylesheet" type="text/css" href="~/vendor/animsition/css/animsition.min.css">

    <link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">

    <link rel="stylesheet" type="text/css" href="~/vendor/daterangepicker/daterangepicker.css">

    <link rel="stylesheet" type="text/css" href="~/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/css/main.css">

</head>
<body>

    <div class="limiter">
        <div class="container-login100" style="background-image: url('@Url.Content("~/images/bg-01.jpg")');">
            <div class="wrap-login100">
                @RenderBody()
            </div>
        </div>
    </div>


    <div id="dropDownSelect1"></div>


    <script src="~/vendor/jquery/jquery-3.2.1.min.js"></script>

    <script src="~/vendor/animsition/js/animsition.min.js"></script>

    <script src="~/vendor/bootstrap/js/popper.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/vendor/select2/select2.min.js"></script>

    <script src="~/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/vendor/daterangepicker/daterangepicker.js"></script>

    <script src="~/vendor/countdowntime/countdowntime.js"></script>

    <script src="~/js/main.js"></script>

</body>
</html>

company.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - company.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/company.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">company.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>      <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li> </li>      <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                        </li>   </li> </li>      <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">users</a>
                        </li>  </li> </li>      <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - company.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>